name: Test PR content into 'development' or 'stage' branches
on:
  pull_request:
    branches:
      - development
      - stage
  
jobs:
  build_docker:
    name: Build the docker container
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    # build container image from source branch  
    - name: Build Container
      run: |-
        docker build -t temp ./docker

    # run container with unit test command
    - name: Run the unit test inside the docker container
      run: docker run -t temp pytest /code/tests/tests_unit/
    
    # run container with integration test command
    - name: Run the regression tests inside the docker container
      run: docker run -t temp /bin/bash -c "python app/api.py > log.txt 2>&1 & pytest /code/tests/tests_integration/"