name: Test content of PRs into 'development' or 'stage' branches
on:
  pull_request:
    branches:
      - development
      - stage
  
jobs:
  build_docker_and_test:
    name: Build the docker container and run tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    # build container image from source branch  
    - name: Build Container
      run: |-
        docker build -t temp .

    # run container with unit test command
    - name: Run the unit test inside the docker container
      run: docker run -t temp pytest /repository/tests/tests_unit/
    
    # run container with integration test command
    - name: Run the integration tests inside the docker container
      run: docker run -t temp /bin/bash -c "python app/api.py > log.txt 2>&1 & pytest /repository/tests/tests_integration/"