name: Build, tag and push docker image to repository 
on:
  pull_request:
    types: [closed]
    branches:
      - development
      - stage
  
jobs:
  build_docker_and_push:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # authenticate with docker hub
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    # Build and tag the image using naming convention {docker-repository}:{branch_name}-{commit_id}
    - name: Build Container image
      run: docker build -t bettmensch88/argo-cd-demo-api:${{ github.base_ref }}-${{  github.sha }} .
          
    # Push Container to registry
    - name: Push Container
      run: docker push bettmensch88/argo-cd-demo-api:${{ github.base_ref }}-${{  github.sha }}